receivers:
  otlp:
    protocols: 
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
processors:
  batch:
exporters:
  logging:
  otlp:
    endpoint: "http://tempo.monitoring.svc.cluster.local:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:55678"
  loki:
    endpoint: "http://loki.monitoring.svc.cluster.local/loki/api/v1/push"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
